-- Metadata and aggregate counts only. No DDL, DML, locks or personal data.
SET SESSION MAX_EXECUTION_TIME=10000;
START TRANSACTION READ ONLY;
SELECT 'V',VERSION(),DATABASE(),@@character_set_server,@@collation_server,@@sql_mode;
SELECT 'T',TABLE_NAME,ENGINE,ROW_FORMAT,TABLE_COLLATION,COALESCE(DATA_LENGTH,0),COALESCE(INDEX_LENGTH,0)
FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() ORDER BY TABLE_NAME;
SELECT 'C',TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION,COLUMN_TYPE,IS_NULLABLE,
COALESCE(CHARACTER_SET_NAME,'-'),COALESCE(COLLATION_NAME,'-'),
IF(COLUMN_DEFAULT IS NULL,'NULL',CONCAT('SHA256:',SHA2(COLUMN_DEFAULT,256))),EXTRA
FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() ORDER BY TABLE_NAME,ORDINAL_POSITION;
SELECT 'I',TABLE_NAME,INDEX_NAME,NON_UNIQUE,SEQ_IN_INDEX,COALESCE(COLUMN_NAME,'-'),COALESCE(SUB_PART,0),INDEX_TYPE
FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX;
SELECT 'F',k.TABLE_NAME,k.CONSTRAINT_NAME,k.ORDINAL_POSITION,k.COLUMN_NAME,k.REFERENCED_TABLE_NAME,k.REFERENCED_COLUMN_NAME,r.UPDATE_RULE,r.DELETE_RULE
FROM information_schema.KEY_COLUMN_USAGE k JOIN information_schema.REFERENTIAL_CONSTRAINTS r
ON r.CONSTRAINT_SCHEMA=k.CONSTRAINT_SCHEMA AND r.TABLE_NAME=k.TABLE_NAME AND r.CONSTRAINT_NAME=k.CONSTRAINT_NAME
WHERE k.CONSTRAINT_SCHEMA=DATABASE() AND k.REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY k.TABLE_NAME,k.CONSTRAINT_NAME,k.ORDINAL_POSITION;
SELECT 'A','exam',COUNT(*) FROM el_exam;
SELECT 'A','paper-state',state,COUNT(*) FROM el_paper GROUP BY state;
SELECT 'A','exam-mode',assessment_type,scoring_mode,COUNT(*) FROM el_exam GROUP BY assessment_type,scoring_mode;
SELECT 'A','dimension-count',COUNT(*) FROM el_competency_dimension;
SELECT 'A','result-count',COUNT(*) FROM el_competency_result;
SELECT 'A','report-count',COUNT(*) FROM el_competency_report;
SELECT 'A','state0-deadline',COUNT(*),COALESCE(SUM(limit_time IS NULL),0),COALESCE(SUM(limit_time<=NOW()),0),COALESCE(SUM(limit_time>NOW()),0) FROM el_paper WHERE state=0;
SELECT 'A','state0-missing-exam',COUNT(*) FROM el_paper p LEFT JOIN el_exam e ON e.id=p.exam_id WHERE p.state=0 AND e.id IS NULL;
SELECT 'A','dimension-identities',SUM(code REGEXP '^D[0-9]+$'),SUM(code REGEXP '^[AB][0-9]+-[0-9]+$') FROM el_competency_dimension;
COMMIT;